kernel: Pass cross-compilation args to make
The derivation for the kernel currently supports building natively on
either x86_64 or aarch64 build machines, but fails when attempting
cross-compilation:

  $ nix-build -A all --arg pkgs '(import ./nixpkgs.nix { }).pkgsCross.aarch64-multiplatform'
  ...
  building '/nix/store/hml25k4h1k5wzs691mxk9kybj4q3dfyg-nitro-enclaves-kernel-aarch64-unknown-linux-gnu-6.6.38.drv'...
  ...
  #
  # configuration written to .config
  #
  make[2]: *** No rule to make target 'Image'.  Stop.
  make[1]: *** [/build/source/Makefile:359: __build_one_by_one] Error 2
  make: *** [Makefile:234: __sub-make] Error 2
  error: builder for '/nix/store/hml25k4h1k5wzs691mxk9kybj4q3dfyg-nitro-enclaves-kernel-aarch64-unknown-linux-gnu-6.6.38.drv' failed with exit code 2;

This particular issue is because the kernel build system auto-detects
and builds for the architecture of the build machine.

Even if we override this architecture by passing the correct make
argument for ARCH, the build still fails because the compiler that gets
picked up as CC is effectively the HOSTCC (from depsBuildBuild):

  gcc: error: unrecognized command-line option '-mlittle-endian'
  gcc: error: unrecognized command-line option '-mlittle-endian'
  make[3]: *** [scripts/Makefile.build:243: scripts/mod/empty.o] Error 1
  make[3]: *** Waiting for unfinished jobs....
  make[3]: *** [scripts/Makefile.build:116: scripts/mod/devicetable-offsets.s] Error 1
  make[2]: *** [Makefile:1200: prepare0] Error 2
  make[1]: *** [/build/source/Makefile:359: __build_one_by_one] Error 2
  make: *** [Makefile:234: __sub-make] Error 2
  error: builder for '/nix/store/b1hw66fngwmz5lvzfjgji6q34a78yccr-nitro-enclaves-kernel-aarch64-unknown-linux-gnu-6.6.38.drv' failed with exit code 2;

In order to use the correct cross-compiler, we have to make sure we use
the prefixed compiler binaries and bintools. Add the necessary make
arguments to forward them from the stdenv build environment variables.

This change unblocks cross-compilation on x86_64-linux build machines to
aarch64-linux via one of the following commands (the first two are
currently equivalent):

  $ nix-build -A all --arg pkgs '(import ./nixpkgs.nix { }).pkgsCross.aarch64-multiplatform'
  /nix/store/gpxqr7gbm3029dwvjc1075692nbzvn1d-enclaves-blobs-aarch64
  $ nix-build -A all --arg pkgs '(import ./nixpkgs.nix { crossSystem.config = "aarch64-unknown-linux-gnu"; })'
  /nix/store/gpxqr7gbm3029dwvjc1075692nbzvn1d-enclaves-blobs-aarch64
  $ nix-build -A all --arg pkgs '(import ./nixpkgs.nix { crossSystem.config = "aarch64-unknown-linux-musl"; })'
  /nix/store/afjxn1rfindxgb511bplqpvn1538q47q-enclaves-blobs-aarch64

Note the following caveats:

- Cross-compiling with this method currently does not produce identical
  kernel and linuxkit binaries compared to the native build. (init, on
  the other hand, is identical.)
- Requesting `crossSystem.config = "aarch64-unknown-linux-gnu";` still
  uses MUSL to build linuxkit and init, due to how nixpkgs handles the
  `pkgsStatic` set by default.

Resolves https://github.com/aws/aws-nitro-enclaves-sdk-bootstrap/issues/35

Signed-off-by: Simon Veith <sveith@amazon.de>