treewide: Use build inputs from appropriate package sets
The init, kernel and linuxkit components consume multiple packages as
`nativeBuildInputs` and `nativeCheckInputs`, i.e. tools that run on the
build machine but produce outputs for the host machine.

They currently take these inputs from the `pkgs` set, i.e. packages for
the host machine. In doing so, they assume that build and host
architecture match.

When this assumption is violated during cross-compilation, incompatible
architecture binaries end up getting pulled into the build environment,
and we see errors such as the following:

  $ nix-build -A all --arg pkgs '(import ./nixpkgs.nix { }).pkgsCross.aarch64-multiplatform'
  these 3 derivations will be built:
    /nix/store/ihdlwg4bpi5lpiy0w5cq4sdzc8ir727j-nitro-enclaves-init-aarch64-unknown-linux-gnu.drv
    /nix/store/qmz5vg05rvfrqh0zkg1shwsrwi6l0mdn-nitro-enclaves-kernel-aarch64-unknown-linux-gnu-6.6.38.drv
    /nix/store/4hwpzdc9byimhq0k24iya8gzpsdaky4q-enclaves-blobs-aarch64.drv
  building '/nix/store/ihdlwg4bpi5lpiy0w5cq4sdzc8ir727j-nitro-enclaves-init-aarch64-unknown-linux-gnu.drv'...
  Running phase: unpackPhase
  /nix/store/l30525lnvzaiwqihqzspgrljmvjfx9j6-stdenv-linux/setup: line 1575: /nix/store/acr7vh74jl7yn1zsmv538bhjs38yxc6s-coreutils-aarch64-unknown-linux-gnu-9.5/bin/date: cannot execute: required file not found
  unpacking source archive /nix/store/dadd9xs8rbr3nszadqhdxgk5f7rjga11-init
  /nix/store/l30525lnvzaiwqihqzspgrljmvjfx9j6-stdenv-linux/setup: line 1001: /nix/store/acr7vh74jl7yn1zsmv538bhjs38yxc6s-coreutils-aarch64-unknown-linux-gnu-9.5/bin/basename: cannot execute: required file not found
  /nix/store/l30525lnvzaiwqihqzspgrljmvjfx9j6-stdenv-linux/setup: line 1064: /nix/store/acr7vh74jl7yn1zsmv538bhjs38yxc6s-coreutils-aarch64-unknown-linux-gnu-9.5/bin/cp: cannot execute: required file not found
  do not know how to unpack source archive /nix/store/dadd9xs8rbr3nszadqhdxgk5f7rjga11-init
  error: builder for '/nix/store/ihdlwg4bpi5lpiy0w5cq4sdzc8ir727j-nitro-enclaves-init-aarch64-unknown-linux-gnu.drv' failed with exit code 1;
         last 6 log lines:
         > Running phase: unpackPhase
         > /nix/store/l30525lnvzaiwqihqzspgrljmvjfx9j6-stdenv-linux/setup: line 1575: /nix/store/acr7vh74jl7yn1zsmv538bhjs38yxc6s-coreutils-aarch64-unknown-linux-gnu-9.5/bin/date: cannot execute: required file not found
         > unpacking source archive /nix/store/dadd9xs8rbr3nszadqhdxgk5f7rjga11-init
         > /nix/store/l30525lnvzaiwqihqzspgrljmvjfx9j6-stdenv-linux/setup: line 1001: /nix/store/acr7vh74jl7yn1zsmv538bhjs38yxc6s-coreutils-aarch64-unknown-linux-gnu-9.5/bin/basename: cannot execute: required file not found
         > /nix/store/l30525lnvzaiwqihqzspgrljmvjfx9j6-stdenv-linux/setup: line 1064: /nix/store/acr7vh74jl7yn1zsmv538bhjs38yxc6s-coreutils-aarch64-unknown-linux-gnu-9.5/bin/cp: cannot execute: required file not found
         > do not know how to unpack source archive /nix/store/dadd9xs8rbr3nszadqhdxgk5f7rjga11-init
         For full logs, run 'nix-store -l /nix/store/ihdlwg4bpi5lpiy0w5cq4sdzc8ir727j-nitro-enclaves-init-aarch64-unknown-linux-gnu.drv'.
  error: 1 dependencies of derivation '/nix/store/4hwpzdc9byimhq0k24iya8gzpsdaky4q-enclaves-blobs-aarch64.drv' failed to build

Clean up the inputs by making sure they are taken from the appropriate
package set:

- Move `gcc` from `buildInputs` to `nativeBuildInputs`, as it is not
  needed on the host platform that we build for (the compiler targeting
  the host platform is implicitly included in stdenv). Take it from
  `buildPackages` rather than pkgs.
- Use the appropriate `targetPrefix` when invoking the compiler
  targeting the host platform, as the unprefixed version was incorrectly
  referencing the `gcc` host package from `pkgs`.
- For the kernel build, add `gcc` also to `depsBuildBuild`, since it is
  needed as the HOSTCC (running on the build platform and producing
  outputs to run on the build platform).
- For the init build, move `glibc.static` from `nativeBuildInputs` to
  `buildInputs`, since it is a library for the host system and not the
  build system.

Signed-off-by: Simon Veith <sveith@amazon.de>